### PR TITLE
Modularize vue components

### PR DESCRIPTION
**Pull request by adw45**

### CODE REVIEW

**Comment by jafern14** [comment]
YOU'RE SO FUCKING ANNOYING

**Comment by jafern14** [comment]
@jward1990 you take care of this shit.

**Comment by jward1990** [comment]
@jafern14 I don't even know what this is

**Comment by jafern14** [comment]
@jward1990 you and i both dude. i don't even know why he's doing this to us. 

i kind of just assume its 💩

**Comment by adw45** [comment]
</3

**Pull request merged**
